//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.07 at 03:19:07 PM IRDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.oorsprong.org/websamples.countryinfo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.integration.schemas;
